defmodule DockerServices.CLI do
  def main([ "bootstrap" ]) do
    DockerServices.Bootstrap.run
  end

  def main([ "help" ]) do
    IO.puts """
    docker_services v#{DockerServices.Version.current}

    Starts services (like redis, memcached, postgres) using docker, exposes environment variables for ports and ensures the data generated by the services are persisted.

    Usage:
      cd project
      docker_services init
      docker_services start
      docker_services stop

    For more information see https://github.com/joakimk/docker_services
    """
  end

  def main(args) do
    IO.puts "Unknown command or arguments: #{inspect(args)}\n"

    main([ "help" ])
  end
end
